# Generated by Django 2.2 on 2021-02-12 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0014_add_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='ratings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
